version: '3.9'
services:
  chat-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chat-app
    restart: unless-stopped
    ports:
      - '8001:8001'
    logging:
      driver: 'loki'
      options:
        loki-url: "http://loki:${LOKI_PORT}/loki/api/v1/push"
    depends_on:
      - redis-db
      - postgres-db

  redis-db:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - 'redis-data:/data'

  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    
  loki:
    image: grafana/loki:latest
    container_name: 'loki'
    restart: unless-stopped
    ports:
      - '${LOKI_PORT}:3100'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT}:3000'
    logging:
      driver: 'loki'
      options:
        loki-url: "http://loki:${LOKI_PORT}/loki/api/v1/push"

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  logs:
    driver: local