version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: unless-stopped
    ports:
      - '8001:8001'
    labels:
      logging: "promtail"
      logging_jobname: "server_logs"
    depends_on:
      - redis-db
      - postgres-db
      - promtail
    networks:
      - app

  redis-db:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - app

  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - app
    
  # migrator:
  #   build:
  #     context: ./migrator
  #     dockerfile: Dockerfile
  #   image: migrator
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #   depends_on:
  #     - postgres-db
  #   networks:
  #     - app

  loki:
    image: grafana/loki:latest
    container_name: 'loki'
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yml
    ports:
      - '3100:3100'
    volumes:
      - './server/config/loki/config.yml:/etc/loki/config.yml'
    networks:
      - app
      - loki

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    container_name: 'promtail'
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - './server/config/promtail/config.yml:/etc/promtail/config.yml'
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - app
      - loki

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - loki
    networks:
      - app
      - loki

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  app:
  loki: