server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: chat_app_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
    pipeline_stages:
    - match:
        selector: '{job="chat_app_logs"}'
        stages:
        - json:
            expressions:
                msg: msg
                user_id: user_id
                chat_id: chat_id
                session_id: session_id
                chats: chats
                message: message
                body: body
        - labels:
            msg: msg
            user_id: user_id
            chat_id: chat_id
            session_id: session_id
            chats: chats
            message: message
            body: body
